/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: {
          50: 'oklch(var(--background-50) / <alpha-value>)',
          100: 'oklch(var(--background-100) / <alpha-value>)',
          200: 'oklch(var(--background-200) / <alpha-value>)',
          300: 'oklch(var(--background-300) / <alpha-value>)',
          400: 'oklch(var(--background-400) / <alpha-value>)',
          500: 'oklch(var(--background-500) / <alpha-value>)',
          600: 'oklch(var(--background-600) / <alpha-value>)',
          700: 'oklch(var(--background-700) / <alpha-value>)',
          800: 'oklch(var(--background-800) / <alpha-value>)',
          900: 'oklch(var(--background-900) / <alpha-value>)',
          950: 'oklch(var(--background-950) / <alpha-value>)',
        },
        foreground: {
          50: 'oklch(var(--foreground-50) / <alpha-value>)',
          100: 'oklch(var(--foreground-100) / <alpha-value>)',
          200: 'oklch(var(--foreground-200) / <alpha-value>)',
          300: 'oklch(var(--foreground-300) / <alpha-value>)',
          400: 'oklch(var(--foreground-400) / <alpha-value>)',
          500: 'oklch(var(--foreground-500) / <alpha-value>)',
          600: 'oklch(var(--foreground-600) / <alpha-value>)',
          700: 'oklch(var(--foreground-700) / <alpha-value>)',
          800: 'oklch(var(--foreground-800) / <alpha-value>)',
          900: 'oklch(var(--foreground-900) / <alpha-value>)',
          950: 'oklch(var(--foreground-950) / <alpha-value>)',
        },
        primary: {
          50: 'oklch(var(--primary-50) / <alpha-value>)',
          100: 'oklch(var(--primary-100) / <alpha-value>)',
          200: 'oklch(var(--primary-200) / <alpha-value>)',
          300: 'oklch(var(--primary-300) / <alpha-value>)',
          400: 'oklch(var(--primary-400) / <alpha-value>)',
          500: 'oklch(var(--primary-500) / <alpha-value>)',
          600: 'oklch(var(--primary-600) / <alpha-value>)',
          700: 'oklch(var(--primary-700) / <alpha-value>)',
          800: 'oklch(var(--primary-800) / <alpha-value>)',
          900: 'oklch(var(--primary-900) / <alpha-value>)',
          950: 'oklch(var(--primary-950) / <alpha-value>)',
        },
        accent: {
          50: 'oklch(var(--accent-50) / <alpha-value>)',
          100: 'oklch(var(--accent-100) / <alpha-value>)',
          200: 'oklch(var(--accent-200) / <alpha-value>)',
          300: 'oklch(var(--accent-300) / <alpha-value>)',
          400: 'oklch(var(--accent-400) / <alpha-value>)',
          500: 'oklch(var(--accent-500) / <alpha-value>)',
          600: 'oklch(var(--accent-600) / <alpha-value>)',
          700: 'oklch(var(--accent-700) / <alpha-value>)',
          800: 'oklch(var(--accent-800) / <alpha-value>)',
          900: 'oklch(var(--accent-900) / <alpha-value>)',
          950: 'oklch(var(--accent-950) / <alpha-value>)',
        },
        secondary: {
          50: 'oklch(var(--secondary-50) / <alpha-value>)',
          100: 'oklch(var(--secondary-100) / <alpha-value>)',
          200: 'oklch(var(--secondary-200) / <alpha-value>)',
          300: 'oklch(var(--secondary-300) / <alpha-value>)',
          400: 'oklch(var(--secondary-400) / <alpha-value>)',
          500: 'oklch(var(--secondary-500) / <alpha-value>)',
          600: 'oklch(var(--secondary-600) / <alpha-value>)',
          700: 'oklch(var(--secondary-700) / <alpha-value>)',
          800: 'oklch(var(--secondary-800) / <alpha-value>)',
          900: 'oklch(var(--secondary-900) / <alpha-value>)',
          950: 'oklch(var(--secondary-950) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['var(--font-body)'],
        body: ['var(--font-body)'],
        heading: ['var(--font-heading)'],
        display: ['var(--font-heading)'],
        serif: ['var(--font-heading)'],
        label: ['var(--font-label)'],
        mono: ['var(--font-label)'],
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-18px)' },
        },
        bob: {
          '0%, 100%': { transform: 'translateY(-10px)' },
          '50%': { transform: 'translateY(12px)' },
        },
        spinSlow: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        slideLoop: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-50%)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.5', transform: 'scale(1.1)' },
        },
        kenburns: {
          '0%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(1.22)' },
        },
        wave: {
          '0%, 100%': { transform: 'scaleY(0.3)' },
          '50%': { transform: 'scaleY(1)' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        letterUp: {
          from: { opacity: '0', transform: 'translateY(0.9em) rotate(8deg)' },
          to: { opacity: '1', transform: 'translateY(0) rotate(0deg)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        tilt: {
          '0%, 100%': { transform: 'rotate(-5deg)' },
          '50%': { transform: 'rotate(5deg)' },
        },
        pingSlow: {
          '0%': { transform: 'scale(1)', opacity: '0.7' },
          '80%, 100%': { transform: 'scale(2.4)', opacity: '0' },
        },
        morph: {
          '0%, 100%': { borderRadius: '42% 58% 63% 37% / 41% 44% 56% 59%', transform: 'rotate(0deg)' },
          '50%': { borderRadius: '63% 37% 41% 59% / 58% 63% 37% 42%', transform: 'rotate(180deg)' },
        },
        sweep: {
          '0%': { transform: 'scaleX(0)' },
          '100%': { transform: 'scaleX(1)' },
        },
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'float-slow': 'float 9s ease-in-out infinite',
        bob: 'bob 3.6s ease-in-out infinite',
        'spin-slow': 'spinSlow 16s linear infinite',
        'spin-slow-rev': 'spinSlow 22s linear infinite reverse',
        marquee: 'marquee 30s linear infinite',
        'marquee-rev': 'marquee 30s linear infinite reverse',
        'marquee-slow': 'marquee 48s linear infinite',
        'pulse-glow': 'pulseGlow 3.6s ease-in-out infinite',
        kenburns: 'kenburns 16s ease-out both',
        'slide-loop': 'slideLoop 20s linear infinite',
        wave: 'wave 1.1s ease-in-out infinite',
        blink: 'blink 1s step-end infinite',
        'letter-up': 'letterUp 0.9s cubic-bezier(0.16, 1, 0.3, 1) both',
        'fade-in': 'fadeIn 1.2s ease-out both',
        tilt: 'tilt 6s ease-in-out infinite',
        'ping-slow': 'pingSlow 2.4s cubic-bezier(0, 0, 0.2, 1) infinite',
        morph: 'morph 10s ease-in-out infinite',
        sweep: 'sweep 1.1s cubic-bezier(0.16, 1, 0.3, 1) both',
      },
    },
  },
  plugins: [],
}